IF  NOT EXISTS(SELECT 1 FROM SYSCOLUMNS WHERE ID = OBJECT_ID('LOJA_TRANSITO') AND NAME = 'CHAVE_NFE_ORIGEM')
BEGIN
   ALTER TABLE LOJA_TRANSITO ADD  CHAVE_NFE_ORIGEM VARCHAR(44)
END

IF NOT exists( SELECT 1 AS QTDE FROM INFORMATION_SCHEMA.COLUMNS C WHERE TABLE_NAME = 'LOJA_VENDA_TROCA_ORIGEM' AND COLUMN_NAME = 'CHAVE_NFE_ORIGEM')
BEGIN 
	EXECUTE ( 'ALTER TABLE LOJA_VENDA_TROCA_ORIGEM ADD CHAVE_NFE_ORIGEM VARCHAR(44)')
END  

IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[W_NOTAS_REFERENCIADAS_DEV]'))
BEGIN
	EXECUTE ('CREATE VIEW W_NOTAS_REFERENCIADAS_DEV AS SELECT VIEW_INICIAL = 1')
END