ALTER VIEW [dbo].[W_NOTAS_REFERENCIADAS_DEV]
AS  
	-- TP 10857125 - Gilvano Santos - #2# - (27/10/2015) - INCLUIR NO XML DA NF-E DE TROCA CHAVE_CFE DE VENDA (CF-E SAT). 
	-- TP 10622549 - Roberto Beda   - #1# - (11/10/2015) - Correção da clausula WHERE para que retorne as notas com TIPO_ORIGEM 8 (trocas e devoluções do dia).
	
	-- 14/10/2015 - FELIPE SILVA   (SS) - SS#6: Alterado para referenciar a reserva somente se o tipo_origem for diferente de 9
	-- 30/09/2015 - TIAGO CARVALHO (SS) - SS#5: Alterado a Sequencia do Join para melhorar a performance
	-- 03/07/2015 - TIAGO CARVALHO (SS) - SS#4: Alterado para levar na nota de cancelamento a nota fiscal de venda quando existir
	-- 22/04/2015 - TIAGO CARVALHO (SS) - SS#3: Alterado para Levar a Chave_nfe_Origem, criado um novo campo na tabela de origem que será alimentada pela customização feita no POS.
	-- 16/04/2015 - Leandro Rocha  (SS) - SS#2: Alterado para retornar a chave da nota de remessa de consignação / Demonstração
	-- 16/04/2015 - BRUNO SILVA    (SS) - SS#1: ALTERADO PARA LEVAR A CHAVE DAS SAIDAS_ORIGEM DAS NOTAS FISCAIS
	
SELECT DISTINCT   
            --CHAVE_NFE = CASE WHEN I.CHAVE_NFE IS NULL THEN NULL ELSE I.CHAVE_NFE END ,  --#2#
			CHAVE_NFE = CASE WHEN ISNULL(I.CHAVE_NFE, NF_ORIGEM.CHAVE_NFE_ORIGEM) IS NULL THEN NULL ELSE ISNULL(I.CHAVE_NFE, NF_ORIGEM.CHAVE_NFE_ORIGEM) END, --#2#
            CHAVEACESSO =	(SELECT TOP 1 SUBSTRING(M.COD_MUNICIPIO_IBGE,1,2)   
								 FROM LCF_LX_MUNICIPIO M (NOLOCK)   
										INNER JOIN LCF_LX_UF U (NOLOCK) ON U.ID_UF = M.ID_UF    
								 WHERE  U.UF = F.UF AND M.DESC_MUNICIPIO = DBO.FX_REPLACE_CARACTER_ESPECIAL_NFE(DEFAULT,F.CIDADE) ) 
								 								 
								+ SUBSTRING(CONVERT(CHAR(10),I.EMISSAO,112),3,4) + RTRIM(F.CGC_CPF) 
								
								+ (SELECT RIGHT('0'+RTRIM(ES.NUMERO_MODELO_FISCAL),2) + CASE WHEN SN.COD_SERIE_SINTEGRA IS NOT NULL  THEN RIGHT('00'+RTRIM(CASE WHEN SN.COD_SERIE_SINTEGRA = 'U' OR SN.COD_SERIE_SINTEGRA = 'UN' THEN '0' ELSE SN.COD_SERIE_SINTEGRA END),3) ELSE RIGHT('00'+RTRIM(CASE WHEN SN.SERIE_NF = 'U' OR SN.SERIE_NF = 'UN' THEN '0' ELSE SN.SERIE_NF END),3) END   
									  FROM SERIES_NF SN (NOLOCK)  
										   INNER JOIN CTB_ESPECIE_SERIE ES (NOLOCK) ON SN.ESPECIE_SERIE = ES.ESPECIE_SERIE   
									  WHERE SERIE_NF = I.SERIE_NF ) 
									  
								+ RIGHT('00000000'+RTRIM(A.NF_NUMERO),9)
                            ,ISNULL(CONVERT(VARCHAR(40), H.NOME_CLIFOR)
                            ,G.CLIENTE_VAREJO) AS FILIAL
                            ,A.SERIE_NF AS SERIE
                            ,A.NF_NUMERO AS NF
                            ,'S' AS ORIGEM_ENTRADA_SAIDA
                            , NF_ORIGEM.NF_ORIGEM
                            , NF_ORIGEM.SERIE_NF_ORIGEM
                            , NF_ORIGEM.MODELO_FISCAL  
                            , NF_ORIGEM.NUMERO_ECF  
                            , NF_ORIGEM.NUMERO_COO
            
            FROM   
                  LOJA_NOTA_FISCAL_ITEM A (NOLOCK)  
            LEFT JOIN LOJA_NOTA_FISCAL B (NOLOCK)	ON B.NF_NUMERO = A.NF_NUMERO AND B.SERIE_NF = A.SERIE_NF AND B.CODIGO_FILIAL = A.CODIGO_FILIAL  
            LEFT JOIN LOJAS_VAREJO E ON E.CODIGO_FILIAL = A.CODIGO_FILIAL   
            LEFT JOIN CADASTRO_CLI_FOR F ON E.FILIAL = F.NOME_CLIFOR   
                  LEFT JOIN CLIENTES_VAREJO G (NOLOCK) ON B.CODIGO_CLIENTE = G.CODIGO_CLIENTE   
                  LEFT JOIN CADASTRO_CLI_FOR H (NOLOCK) ON B.COD_CLIFOR = H.COD_CLIFOR   
             INNER JOIN (SELECT F.CODIGO_FILIAL, F.NF_NUMERO AS NF_ORIGEM, F.SERIE_NF AS SERIE_NF_ORIGEM,  F.CHAVE_NFE  AS CHAVE_NFE_ORIGEM, A.NUMERO_FISCAL_TROCA AS NF_TROCA, A.SERIE_NF_ENTRADA AS SERIE_NF_TROCA,
								'2D' AS MODELO_FISCAL, ISNULL(E.ID_EQUIPAMENTO, 1) AS NUMERO_ECF , CONVERT(Int, E.NUMERO_CUPOM_FISCAL) AS NUMERO_COO  
						 FROM 
								LOJA_VENDA_PGTO A
								INNER JOIN LOJA_VENDA B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TERMINAL = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
								INNER JOIN LOJA_VENDA_TROCA_ORIGEM C ON C.CODIGO_FILIAL = B.CODIGO_FILIAL AND C.DATA_VENDA = B.DATA_VENDA AND C.TICKET = B.TICKET /*SS#3 AND C.TICKET <> C.TICKET_ORIGEM */
								INNER JOIN LOJA_VENDA D ON D.CODIGO_FILIAL = C.CODIGO_FILIAL AND D.DATA_VENDA = C.DATA_VENDA_ORIGEM AND D.TICKET = C.TICKET_ORIGEM 
								INNER JOIN LOJA_VENDA_PGTO E ON E.CODIGO_FILIAL = D.CODIGO_FILIAL AND E.TERMINAL = D.TERMINAL AND E.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA 
								INNER JOIN LOJA_NOTA_FISCAL F ON F.CODIGO_FILIAL = E.CODIGO_FILIAL AND F.NF_NUMERO = E.NUMERO_FISCAL_VENDA AND F.SERIE_NF = E.SERIE_NF_SAIDA AND F.STATUS_NFE = '5'
							WHERE C.CHAVE_NFE_ORIGEM IS NULL /*SS#3 */
						   /*--INICIO #2#*/
							UNION ALL
														
							SELECT	F.CODIGO_FILIAL, CONVERT(CHAR(18), F.CF_NUMERO) AS NF_ORIGEM, F.SERIE_NF AS SERIE_NF_ORIGEM,  F.CHAVE_CFE AS CHAVE_NFE_ORIGEM, A.NUMERO_FISCAL_TROCA AS NF_TROCA, 
									A.SERIE_NF_ENTRADA AS SERIE_NF_TROCA,  H.NUMERO_MODELO_FISCAL AS MODELO_FISCAL, ISNULL(E.ID_EQUIPAMENTO, 1) AS NUMERO_ECF , NULL AS NUMERO_COO  
							FROM 
							LOJA_VENDA_PGTO A
							INNER JOIN LOJA_VENDA B ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TERMINAL = B.TERMINAL AND A.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
							INNER JOIN LOJA_VENDA_TROCA_ORIGEM C ON C.CODIGO_FILIAL = B.CODIGO_FILIAL AND C.DATA_VENDA = B.DATA_VENDA AND C.TICKET = B.TICKET AND C.TICKET <> C.TICKET_ORIGEM 
							INNER JOIN LOJA_VENDA D ON D.CODIGO_FILIAL = C.CODIGO_FILIAL AND D.DATA_VENDA = C.DATA_VENDA_ORIGEM AND D.TICKET = C.TICKET_ORIGEM 
							INNER JOIN LOJA_VENDA_PGTO E ON E.CODIGO_FILIAL = D.CODIGO_FILIAL AND E.TERMINAL = D.TERMINAL AND E.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA 
							INNER JOIN LOJA_CF_SAT F ON F.CODIGO_FILIAL = E.CODIGO_FILIAL AND F.GUID_VENDA_SAT = E.GUID_VENDA_SAT AND F.STATUS_CFE = '5'
							AND F.TERMINAL = E.TERMINAL AND F.LANCAMENTO_CAIXA = E.LANCAMENTO_CAIXA 
							INNER JOIN SERIES_NF G ON F.SERIE_NF = G.SERIE_NF
							INNER JOIN CTB_ESPECIE_SERIE H ON H.ESPECIE_SERIE = G.ESPECIE_SERIE
						  /*--FIM #2#*/
						 ) AS NF_ORIGEM ON NF_ORIGEM.NF_TROCA = b.NF_NUMERO AND NF_ORIGEM.SERIE_NF_TROCA = B.SERIE_NF 
				
			LEFT JOIN LOJA_NOTA_FISCAL I ON I.CODIGO_FILIAL = NF_ORIGEM.CODIGO_FILIAL AND I.NF_NUMERO = NF_ORIGEM.NF_ORIGEM AND I.SERIE_NF = NF_ORIGEM.SERIE_NF_ORIGEM --#2#
			LEFT JOIN LOJA_CF_SAT J ON J.CODIGO_FILIAL = NF_ORIGEM.CODIGO_FILIAL AND CONVERT(CHAR(18), J.CF_NUMERO) = NF_ORIGEM.NF_ORIGEM AND J.SERIE_NF = NF_ORIGEM.SERIE_NF_ORIGEM --#2#
		WHERE   
		A.NF_NUMERO IS NOT NULL AND	 B.TIPO_ORIGEM IN (2, 8) AND B.RECEBIMENTO = 1	-- #1#

	UNION ALL
	
	/*SS#4 */
	SELECT	DISTINCT
			CHAVE_NFE =  F.CHAVE_NFE  ,
			CHAVEACESSO = '',
			V.FILIAL AS FILIAL,
			C.SERIE_NF_ENTRADA AS SERIE,
			C.NUMERO_FISCAL_TROCA AS NF,
			'S' AS ORIGEM_ENTRADA_SAIDA,
			'' AS NF_ORIGEM ,
			'' AS SERIE_NF_ORIGEM,
			'' AS MODELO_FISCAL,
			'' AS NUMERO_ECF,
			'' AS NUMERO_COO
	FROM LOJA_VENDA_PGTO  C(NOLOCK)
	INNER JOIN LOJA_NOTA_FISCAL F(NOLOCK) ON F.CODIGO_FILIAL = C.CODIGO_FILIAL AND F.NF_NUMERO = C.NUMERO_FISCAL_VENDA AND F.SERIE_NF = C.SERIE_NF_SAIDA AND F.STATUS_NFE = '5'
	INNER JOIN LOJAS_VAREJO V (NOLOCK)ON c.CODIGO_FILIAL = V.CODIGO_FILIAL
	INNER JOIN LOJA_NOTA_FISCAL T(NOLOCK) ON T.CODIGO_FILIAL = C.CODIGO_FILIAL AND T.NF_NUMERO = C.NUMERO_FISCAL_CANCELAMENTO AND T.SERIE_NF = C.SERIE_NF_CANCELAMENTO  

	union all	
	/*SS#3 */
	SELECT	DISTINCT
			CHAVE_NFE =  C.CHAVE_NFE_ORIGEM ,
			CHAVEACESSO = '',
			V.FILIAL AS FILIAL,
			N.SERIE_NF AS SERIE,
			N.NF_NUMERO AS NF,
			'S' AS ORIGEM_ENTRADA_SAIDA,
			'' AS NF_ORIGEM ,
			'' AS SERIE_NF_ORIGEM,
			'' AS MODELO_FISCAL,
			'' AS NUMERO_ECF,
			'' AS NUMERO_COO
	FROM LOJA_VENDA D
	INNER JOIN LOJA_VENDA_PGTO E ON E.CODIGO_FILIAL = D.CODIGO_FILIAL AND E.TERMINAL = D.TERMINAL AND E.LANCAMENTO_CAIXA = D.LANCAMENTO_CAIXA 
	INNER JOIN LOJAS_VAREJO V ON D.CODIGO_FILIAL = V.CODIGO_FILIAL
	INNER JOIN LOJA_NOTA_FISCAL N ON E.NUMERO_FISCAL_TROCA = N.NF_NUMERO AND E.SERIE_NF_ENTRADA = N.SERIE_NF AND E.CODIGO_FILIAL = N.CODIGO_FILIAL 
	/*SS#4 */
	INNER JOIN LOJA_VENDA_TROCA_ORIGEM C ON D.CODIGO_FILIAL = C.CODIGO_FILIAL AND D.DATA_VENDA = C.DATA_VENDA AND D.TICKET = C.TICKET
	WHERE C.CHAVE_NFE_ORIGEM IS NOT NULL
	
	UNION ALL
	
	/* SS#2 */
	SELECT  DISTINCT
			CHAVE_NFE =  NF_ORIGEM.CHAVE_NFE_ORIGEM ,
			CHAVEACESSO = '',
			E.FILIAL,
			B.SERIE_NF AS SERIE,
			B.NF_NUMERO AS NF,
			'E' AS ORIGEM_ENTRADA_SAIDA,
			NF_ORIGEM.NF_ORIGEM ,
			NF_ORIGEM.SERIE_NF_ORIGEM,
			'' AS  MODELO_FISCAL,
			'' AS NUMERO_ECF,
			'' AS NUMERO_COO
	FROM LOJA_NOTA_FISCAL B
	INNER JOIN LOJAS_VAREJO E ON E.CODIGO_FILIAL = B.CODIGO_FILIAL  
	INNER JOIN LOJAS_NATUREZA_OPERACAO NAT ON NAT.NATUREZA_OPERACAO_CODIGO = B.NATUREZA_OPERACAO_CODIGO
	INNER JOIN CTB_LX_TIPO_OPERACAO CT ON NAT.CTB_TIPO_OPERACAO = CT.CTB_TIPO_OPERACAO
	INNER JOIN (SELECT	C.NUMERO_NF_TRANSFERENCIA AS  NF_ORIGEM, C.SERIE_NF_ENTRADA AS SERIE_NF_ORIGEM, E.CODIGO_FILIAL AS CODIGO_FILIAL_ORIGEM, D.CHAVE_NFE_ORIGEM,
						A.NUMERO_NF_TRANSFERENCIA AS NF_SAIDA, A.SERIE_NF AS SERIE_NF_SAIDA, F.CODIGO_FILIAL AS CODIGO_FILIAL_SAIDA
				FROM LOJA_SAIDAS A
				INNER JOIN LOJA_SAIDAS_ORIGEM	B
					ON A.ROMANEIO_PRODUTO = B.ROMANEIO_PRODUTO
					AND A.FILIAL = B.FILIAL
				INNER JOIN LOJA_ENTRADAS C
					ON B.ROMANEIO_PRODUTO_ENTRADA = C.ROMANEIO_PRODUTO
					AND C.FILIAL_ORIGEM = B.FILIAL_ENTRADA
				INNER JOIN LOJA_TRANSITO D
					ON C.ROMANEIO_NF_SAIDA = D.ROMANEIO_NF_SAIDA
					AND C.FILIAL = D.FILIAL
					AND C.NUMERO_NF_TRANSFERENCIA =D.NUMERO_NF_TRANSFERENCIA
					AND C.FILIAL_ORIGEM = D.FILIAL_ORIGEM
					AND C.SERIE_NF_ENTRADA = D.SERIE_NF_ENTRADA
				INNER JOIN LOJAS_VAREJO E
					ON E.FILIAL = C.FILIAL_ORIGEM
				INNER JOIN LOJAS_VAREJO F
					ON F.FILIAL = C.FILIAL
				GROUP BY C.NUMERO_NF_TRANSFERENCIA, C.SERIE_NF_ENTRADA, E.CODIGO_FILIAL, D.CHAVE_NFE_ORIGEM, A.NUMERO_NF_TRANSFERENCIA , A.SERIE_NF , F.CODIGO_FILIAL )  NF_ORIGEM
	ON	B.NF_NUMERO = NF_ORIGEM.NF_SAIDA AND B.SERIE_NF = NF_ORIGEM.SERIE_NF_SAIDA AND B.CODIGO_FILIAL = NF_ORIGEM.CODIGO_FILIAL_SAIDA		
	WHERE CT.TIPO_OPERACAO IN('D','E','T')
	
	UNION ALL
	
	SELECT DISTINCT 
			CHAVE_NFE =  NF_ORIGEM.CHAVE_NFE,
			CHAVEACESSO = '',
			LOJAS_VAREJO.FILIAL,
			LOJA_NOTA_FISCAL.SERIE_NF AS SERIE,
			LOJA_NOTA_FISCAL.NF_NUMERO AS NF,
			'E' AS ORIGEM_ENTRADA_SAIDA,
			NF_ORIGEM.NF_NUMERO ,
			NF_ORIGEM.SERIE_NF,
			'' AS  MODELO_FISCAL,
			'' AS NUMERO_ECF,
			'' AS NUMERO_COO
	FROM LOJA_NOTA_FISCAL (NOLOCK)
	INNER JOIN LOJAS_VAREJO (NOLOCK)
		ON LOJAS_VAREJO.CODIGO_FILIAL = LOJA_NOTA_FISCAL.CODIGO_FILIAL  
	INNER JOIN LOJA_RESERVA (NOLOCK)
		ON LOJA_RESERVA.NUMERO_NF_RETORNO = LOJA_NOTA_FISCAL.NF_NUMERO AND LOJA_RESERVA.SERIE_NF_RETORNO = LOJA_NOTA_FISCAL.SERIE_NF AND LOJA_RESERVA.FILIAL = LOJAS_VAREJO.FILIAL
	INNER JOIN LOJA_NOTA_FISCAL AS NF_ORIGEM (NOLOCK)
		ON NF_ORIGEM.NF_NUMERO = LOJA_RESERVA.NUMERO_NF AND NF_ORIGEM.SERIE_NF = LOJA_RESERVA.SERIE_NF AND NF_ORIGEM.CODIGO_FILIAL = LOJAS_VAREJO.CODIGO_FILIAL
	LEFT JOIN LOJA_NOTA_FISCAL_REFERENCIADA_ITEM (NOLOCK) /*SS#6*/
			ON LOJA_NOTA_FISCAL_REFERENCIADA_ITEM.NF_NUMERO = LOJA_NOTA_FISCAL.NF_NUMERO
						  AND LOJA_NOTA_FISCAL_REFERENCIADA_ITEM.SERIE_NF = LOJA_NOTA_FISCAL.SERIE_NF
						  AND LOJA_NOTA_FISCAL_REFERENCIADA_ITEM.CODIGO_FILIAL = LOJA_NOTA_FISCAL.CODIGO_FILIAL
	WHERE ISNULL(LOJA_NOTA_FISCAL_REFERENCIADA_ITEM.TIPO_ORIGEM, 0) <> 9