CREATE TRIGGER [DBO].[LXI_ANM_LOJA_VENDA] ON [DBO].[LOJA_VENDA] 
		FOR INSERT NOT 
		FOR REPLICATION 
	AS 
	/*Evita pulo sequencial nfce - Rafael Medeiros Soma*/ 
	UPDATE A SET A.SEQUENCIAL=B.SEQUENCIAL 
		FROM FATURAMENTO_SEQUENCIAIS A 
		JOIN 
			(
				SELECT SERIE_NF,MAX(NF_NUMERO) AS SEQUENCIAL 
					FROM LOJA_NOTA_FISCAL (nolock)
					WHERE SERIE_NF = '65' and emissao>=getdate()-10 
					GROUP BY SERIE_NF
			) B 
			ON	A.SERIE_NF = B.SERIE_NF 
				AND A.SEQUENCIAL <> B.SEQUENCIAL 
	WHERE A.SERIE_NF = '65'