DECLARE @CODIGO_FILIAL varchar(6), @NF_NUMERO varchar(15) ,@SERIE_NF varchar(6)
		  
DECLARE curNfErro CURSOR FOR 
SELECT  A.CODIGO_FILIAL , A.NF_NUMERO ,A.SERIE_NF 
	FROM LOJA_NOTA_FISCAL A (NOLOCK)
	LEFT JOIN LOJA_NOTA_FISCAL_ITEM B (NOLOCK)
		ON A.NF_NUMERO  =B.NF_NUMERO AND A.SERIE_NF =B.SERIE_NF AND A.CODIGO_FILIAL  =B.CODIGO_FILIAL 
	LEFT JOIN LOJA_NOTA_FISCAL_IMPOSTO C (NOLOCK)
		ON A.NF_NUMERO  =C.NF_NUMERO AND A.SERIE_NF =C.SERIE_NF AND A.CODIGO_FILIAL  =C.CODIGO_FILIAL 
	WHERE A.STATUS_NFE IN(49,59,70)
		AND A.PROTOCOLO_CANCELAMENTO_NFE IS NOT NULL
		AND A.EMISSAO >=getdate() - 40
		AND (QTDE_TOTAL <> 0 or VALOR_TOTAL_ITENS <> 0 or VALOR_TOTAL<>0 or NOTA_CANCELADA <> 1
			or ISNULL(b.QTDE_ITEM,0)<>0 OR ISNULL(b.VALOR_ITEM,0)<>0 OR ISNULL(b.PRECO_UNITARIO,0)<>0 OR ISNULL(b.DESCONTO_ITEM,0)<>0 
			OR ISNULL(c.TAXA_IMPOSTO,0)<>0 OR ISNULL(c.VALOR_IMPOSTO,0)<>0 OR ISNULL(c.BASE_IMPOSTO,0)<>0 
			 )
	GROUP BY A.CODIGO_FILIAL , A.NF_NUMERO ,A.SERIE_NF  
	OPEN curNfErro
	FETCH NEXT FROM curNfErro INTO @CODIGO_FILIAL, @NF_NUMERO, @SERIE_NF  
	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE LOJA_NOTA_FISCAL SET QTDE_TOTAL =0,VALOR_TOTAL_ITENS=0,VALOR_TOTAL=0,NOTA_CANCELADA=1,VALOR_CANCELADO=VALOR_TOTAL,QTDE_CANCELADA=QTDE_TOTAL WHERE NF_NUMERO=@NF_NUMERO AND SERIE_NF =@SERIE_NF AND CODIGO_FILIAL =@CODIGO_FILIAL 
		UPDATE LOJA_NOTA_FISCAL_ITEM SET QTDE_ITEM=0,VALOR_ITEM=0,PRECO_UNITARIO=0,DESCONTO_ITEM=0 WHERE NF_NUMERO=@NF_NUMERO AND SERIE_NF =@SERIE_NF AND CODIGO_FILIAL =@CODIGO_FILIAL 
		UPDATE LOJA_NOTA_FISCAL_IMPOSTO SET TAXA_IMPOSTO=0,VALOR_IMPOSTO=0,BASE_IMPOSTO=0  WHERE NF_NUMERO=@NF_NUMERO AND SERIE_NF =@SERIE_NF AND CODIGO_FILIAL =@CODIGO_FILIAL 
	
		FETCH NEXT FROM curNfErro INTO @CODIGO_FILIAL, @NF_NUMERO, @SERIE_NF  
	END
	
CLOSE curNfErro
DEALLOCATE curNfErro


