 IF EXISTS (SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'NFE_WEB_SERVICE')
BEGIN
	UPDATE PARAMETROS SET VALOR_ATUAL='2' WHERE PARAMETRO='NFE_WEB_SERVICE' AND VALOR_ATUAL<>'2'
	UPDATE PARAMETROS_LOJA SET VALOR_ATUAL='2' WHERE PARAMETRO='NFE_WEB_SERVICE' AND VALOR_ATUAL<>'2'
END
IF NOT EXISTS (SELECT 1 FROM PARAMETROS WHERE PARAMETRO = 'NFE_WEB_SERVICE')
BEGIN
	INSERT INTO PARAMETROS 
		(PARAMETRO, DESC_PARAMETRO, PENULT_ATUALIZACAO, ULT_ATUALIZACAO, 
		TIPO_DADO, VALOR_DEFAULT, VALOR_ATUAL, GLOBAL, 
		ENVIA_PARA_LOJA, PERMITE_POR_LOJA, PERMITE_POR_TERMINAL, PERMITE_ALTERAR_NA_LOJA, PERMITE_ALTERAR_NO_TERMINAL, 
		NOTA_PROGRAMADOR)
	VALUES
		('NFE_WEB_SERVICE', 'Indica qual o Web Service utilizado para emissao de NF-e (1:Mid-e, 2: Dynamicca)', GETDATE(), GETDATE(), 
		'I', '1', '1', '0', 
		'1', '1', '0', '0', '0',
		'')
END