IF NOT EXISTS (SELECT * from sys.objects where name ='ANM_CONTROLE_BOLETA_VENDA' )
	BEGIN
	CREATE TABLE ANM_CONTROLE_BOLETA_VENDA
	(
	DATA DATETIME NOT NULL, 
	LOJA_VAREJO CHAR(6) NOT NULL, 
	VENDEDOR CHAR(4) NOT NULL, 
	CAIXA CHAR(4) NOT NULL, 
	CONTROLE CHAR(6) NOT NULL 

	CONSTRAINT [XPKANM_CONTROLE_BOLETA_VENDA] PRIMARY KEY CLUSTERED 
	(
		[DATA] DESC,
		[LOJA_VAREJO] DESC,
		[VENDEDOR] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

