IF NOT EXISTS (SELECT 1 FROM SYS.objects WHERE name='SS_LOJA_TROCA_ORIGEM' AND TYPE='U')
BEGIN 
	CREATE TABLE [dbo].[SS_LOJA_TROCA_ORIGEM](	CODIGO_FILIAL			char(6)			NOT NULL,
												TICKET					char(8)			NOT NULL,
												DATA_VENDA				datetime		NOT NULL,
												TERMINAL				char(3)			NOT NULL,
												NUMERO_CUPOM_FISCAL		VARCHAR(8)		NOT NULL,
												ECF						smallint		NOT NULL,
												PRODUTO					char(12)		NOT NULL,
												PRECO_LIQUIDO			NUMERIC(22,2)	NOT NULL,
												QTDE_VENDA				INT				NOT NULL,
												QTDE_TROCA				INT				NOT NULL,
												CHAVE_NFE				VARCHAR(44)		NULL,
												DATA_PARA_TRANSFERENCIA	DATETIME		NOT NULL,
												

	CONSTRAINT [PK_SS_LOJA_TROCA_ORIGEM] PRIMARY KEY NONCLUSTERED 
	(
		CODIGO_FILIAL		ASC,
		TICKET				ASC,
		DATA_VENDA			ASC,
		TERMINAL			ASC,
		NUMERO_CUPOM_FISCAL ASC,
		ECF					ASC,
		PRODUTO				ASC
			
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
	) ON [PRIMARY]
END 