IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_SS_LOJA_VENDA_TROCA_ORIGEM]') AND type in (N'P', N'PC'))
BEGIN
	EXECUTE ('CREATE PROCEDURE PROC_SS_LOJA_VENDA_TROCA_ORIGEM AS SELECT PROCEDURE_INICIAL = 1')
END