/*Tiago Carvalho (SS) - 10/05/2015 - Corrigido o saldo de troca quando não existe o resgistro na loja para não retornar null*/
ALTER VIEW W_SS_LOJA_TROCA_ORIGEM_SALDO
AS
SELECT 	ISNULL(B.CODIGO_FILIAL,A.CODIGO_FILIAL)				AS CODIGO_FILIAL,
		ISNULL(B.TICKET,A.TICKET)							AS TICKET,
		ISNULL(B.DATA_VENDA,A.DATA_VENDA)					AS DATA_VENDA,
		ISNULL(B.TERMINAL,A.TERMINAL)						AS TERMINAL,
		ISNULL(B.NUMERO_CUPOM_FISCAL,A.NUMERO_CUPOM_FISCAL) AS NUMERO_CUPOM_FISCAL,
		ISNULL(B.ECF,A.ECF)									AS ECF,
		ISNULL(B.PRODUTO,A.PRODUTO)							AS PRODUTO,
		ISNULL(B.PRECO_LIQUIDO,A.PRECO_LIQUIDO)				AS PRECO_LIQUIDO,
		ISNULL(B.QTDE_VENDA,isnull(A.QTDE_VENDA,0))			AS QTDE_VENDA ,
		ISNULL(B.QTDE_TROCA,isnull(A.QTDE_TROCA,0))			AS QTDE_TROCA,
		ISNULL(B.CHAVE_NFE,A.CHAVE_NFE)						AS CHAVE_NFE
		FROM SS_LOJA_TROCA_ORIGEM A WITH (NOLOCK)
FULL JOIN (	SELECT CODIGO_FILIAL,
					TICKET,
					DATA_VENDA,
					TERMINAL,
					NUMERO_CUPOM_FISCAL,
					ECF,
					PRODUTO,
					PRECO_LIQUIDO=MAX(PRECO_LIQUIDO),
					SUM(QTDE_VENDA) AS QTDE_VENDA ,
					SUM(QTDE_TROCA) AS QTDE_TROCA,
					MAX(CHAVE_NFE)  AS CHAVE_NFE 
			FROM (	SELECT
						A.CODIGO_FILIAL,
						A.TICKET,
						A.DATA_VENDA,
						B.TERMINAL,
						C.NUMERO_CUPOM_FISCAL,
						ECF =isnull((SELECT TOP 1 ECF FROM LOJA_CONTROLE_FISCAL CF WITH(NOLOCK) WHERE CF.CODIGO_FILIAL =A.CODIGO_FILIAL AND CF.TERMINAL = C.TERMINAL AND CF.ID_EQUIPAMENTO = C.ID_EQUIPAMENTO ),b.terminal),
						A.PRODUTO,
						A.PRECO_LIQUIDO,
						A.QTDE AS QTDE_VENDA,
						NULL AS QTDE_TROCA,
						NF.CHAVE_NFE
						FROM LOJA_VENDA_PRODUTO A WITH (NOLOCK)
						INNER JOIN LOJA_VENDA B
							ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.TICKET = B.TICKET AND A.DATA_VENDA = B.DATA_VENDA 
						INNER JOIN LOJA_VENDA_PGTO C
							ON C.CODIGO_FILIAL = B.CODIGO_FILIAL AND C.TERMINAL = B.TERMINAL AND C.LANCAMENTO_CAIXA = B.LANCAMENTO_CAIXA 
						LEFT JOIN LOJA_NOTA_FISCAL NF
							ON NF.NF_NUMERO = C.NUMERO_FISCAL_VENDA AND NF.SERIE_NF = C.SERIE_NF_SAIDA AND NF.CODIGO_FILIAL = C.CODIGO_FILIAL 
						WHERE A.DATA_VENDA = CONVERT(VARCHAR(12),GETDATE(),112)
					UNION ALL
					SELECT	A.CODIGO_FILIAL_ORIGEM,
							A.TICKET_ORIGEM as TICKET ,
							A.DATA_VENDA_ORIGEM,
							A.TERMINAL_ORIGEM,
							A.NUMERO_CUPOM_FISCAL_ORIGEM,
							A.ECF_ORIGEM,
							A.PRODUTO,
							NULL AS PRECO_LIQUIDO,
							NULL AS QTDE_VENDA,
							A.QTDE AS QTDE_TROCA,
							CHAVE_NFE = NULL
						FROM LOJA_VENDA_TROCA A WITH (NOLOCK)
						WHERE A.DATA_VENDA = CONVERT(VARCHAR(12),GETDATE(),112)
							AND A.CODIGO_FILIAL_ORIGEM IS NOT NULL
						
				  ) DADOS_LOJA
			GROUP BY CODIGO_FILIAL,
			TICKET,
			DATA_VENDA,
			TERMINAL,
			NUMERO_CUPOM_FISCAL,
			ECF,
			PRODUTO
			) AS B
	ON A.CODIGO_FILIAL = B.CODIGO_FILIAL AND A.DATA_VENDA = B.DATA_VENDA AND A.TICKET = B.TICKET AND A.PRODUTO = B.PRODUTO 

