IF NOT EXISTS (SELECT * FROM SYS.VIEWS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[W_SS_LOJA_TROCA_ORIGEM_SALDO]'))
BEGIN
	EXECUTE ('CREATE VIEW W_SS_LOJA_TROCA_ORIGEM_SALDO AS SELECT VIEW_INICIAL = 1')
END